In [2]:
import numpy as np

In [3]:
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'PackageLoader',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_import_tools',
 '_mat',
 'abs',
 'absolut

In [6]:
dir(np.random)

['Lock',
 'RandomState',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_numpy_tester',
 'absolute_import',
 'bench',
 'beta',
 'binomial',
 'bytes',
 'chisquare',
 'choice',
 'dirichlet',
 'division',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_state',
 'gumbel',
 'hypergeometric',
 'info',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'np',
 'operator',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'print_function',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_state',
 'shuffle',
 'standard_cauchy',
 'standard_exponential',
 'standard_gamma',
 'standard_normal',
 'standard_t',
 'test',
 'triangular',
 'uniform',
 'vonmises',
 'wald',
 'warnings

In [7]:
help(np.random)

Help on package numpy.random in numpy:

NAME
    numpy.random

DESCRIPTION
    Random Number Generation
    
    ==================== =========================================================
    Utility functions
    random_sample        Uniformly distributed floats over ``[0, 1)``.
    random               Alias for `random_sample`.
    bytes                Uniformly distributed random bytes.
    random_integers      Uniformly distributed integers in a given range.
    permutation          Randomly permute a sequence / generate a random sequence.
    shuffle              Randomly permute a sequence in place.
    seed                 Seed the random number generator.
    choice               Random sample from 1-D array.
    
    ==================== =========================================================
    
    ==================== =========================================================
    Compatibility functions
    rand                 Uniformly distributed values.
    randn

In [8]:
from numpy import random

In [10]:
random.random(10)

array([ 0.85016806,  0.98185792,  0.37167047,  0.31908073,  0.87622489,
        0.77543419,  0.38709328,  0.7826123 ,  0.86422428,  0.01393861])

In [11]:
workex=[15,10,2,5,2,0,0,2,0,0,4,3]

In [13]:
len(workex)

12

In [12]:
type(workex)

list

In [16]:
gender=("Male","Male","Male","Female","Female","Male","Male","Male","Male","Male","Male","Male")

In [17]:
len(gender)

12

In [18]:
type(gender)

tuple

In [19]:
workex[0]

15

In [20]:
workex[1]

10

In [21]:
workex[0]=25

In [22]:
workex

[25, 10, 2, 5, 2, 0, 0, 2, 0, 0, 4, 3]

In [23]:
gender[0]


'Male'

In [24]:
gender[0]='Female'

TypeError: 'tuple' object does not support item assignment

In [25]:
names=['Ajay','Vivek','Lakshay','Kalpana','Kirti','Ravinder','Dara','Prateek','Sarthak','Vivek','Ankit','Nishit']

In [26]:
type(names)

list

In [27]:
names+"Ramesh"

TypeError: can only concatenate list (not "str") to list

In [28]:
names+["Ramesh"]

['Ajay',
 'Vivek',
 'Lakshay',
 'Kalpana',
 'Kirti',
 'Ravinder',
 'Dara',
 'Prateek',
 'Sarthak',
 'Vivek',
 'Ankit',
 'Nishit',
 'Ramesh']

In [30]:
gender+("Male")

TypeError: can only concatenate tuple (not "str") to tuple

In [31]:
newstring2='Hello World's'


SyntaxError: invalid syntax (<ipython-input-31-8c5b85561ed9>, line 1)

In [32]:
newstring2="Hello World's"


In [33]:
newstring2

"Hello World's"

In [34]:
import numpy as np

In [35]:
a=np.array([10,24,32,16])

In [36]:
type(a)

numpy.ndarray

In [37]:
a

array([10, 24, 32, 16])

In [38]:
workex


[25, 10, 2, 5, 2, 0, 0, 2, 0, 0, 4, 3]

In [39]:
a.ndim

1

In [40]:
a.shape

(4,)

In [41]:
listoflists=[[1,2,3,4],[10,25,46,89]]

In [42]:
listoflists

[[1, 2, 3, 4], [10, 25, 46, 89]]

In [43]:
b=np.array(listoflists)

In [44]:
b

array([[ 1,  2,  3,  4],
       [10, 25, 46, 89]])

In [45]:
b.shape

(2, 4)

In [46]:
b.ndim

2

In [47]:
a

array([10, 24, 32, 16])

In [48]:
print(a)

[10 24 32 16]


In [49]:
print(workex)

[25, 10, 2, 5, 2, 0, 0, 2, 0, 0, 4, 3]


In [50]:
print(np.array(workex))

[25 10  2  5  2  0  0  2  0  0  4  3]


In [51]:
b.reshape(8,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [10],
       [25],
       [46],
       [89]])

In [52]:
c=b.reshape(8,1)

In [53]:
type(c)

numpy.ndarray

In [55]:
c.shape

(8, 1)

In [ ]:
c.ndim

# trying to show markdown
## test

In [58]:
'''this
is
example
of multiple 
line comments
'''
2+3

5

In [59]:
1234567891112122*237837383819911

293626397370171850226357061142

In [61]:
d=str(293626397370171850226357061142)

In [62]:
d

'293626397370171850226357061142'

In [63]:
d+"ajay"

'293626397370171850226357061142ajay'

In [64]:
int(d)

293626397370171850226357061142

In [67]:
int(d)*(0.0005)

1.4681319868508593e+26

In [68]:
range(10,50)

range(10, 50)

In [69]:
rr=range(10,50)

In [70]:
print(rr)

range(10, 50)


In [73]:
for a in range(10,15):
print(a)

IndentationError: expected an indented block (<ipython-input-73-63bcc54e1062>, line 2)

In [75]:
for a in range(10,15):
    print(a)

10
11
12
13
14


In [77]:
np.arange(10,15)

array([10, 11, 12, 13, 14])

In [78]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [80]:
np.zeros((3,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [81]:
np.arange(10,16)

array([10, 11, 12, 13, 14, 15])

In [82]:
np.arange(10,16).reshape(3,2)

array([[10, 11],
       [12, 13],
       [14, 15]])

In [83]:
print(np.arange(10,16).reshape(3,2))

[[10 11]
 [12 13]
 [14 15]]


In [84]:
d=np.arange(10,16).reshape(3,2)

In [85]:
d.flatten()

array([10, 11, 12, 13, 14, 15])

In [86]:
list(d.flatten())

[10, 11, 12, 13, 14, 15]